export const APP_CONSTANTS = {
  WATER_GOAL_ML: 3000,
  WATER_QUICK_ADD_OPTIONS: [250, 500, 750, 1000],
  MAX_WEIGHT_ENTRIES_PER_PAGE: 30,
  MAX_FOOD_ENTRIES_PER_PAGE: 50,
  MAX_WORKOUT_LOGS_PER_PAGE: 20,
  DEFAULT_WORKOUT_DURATION: 60,
  STREAK_RESET_HOURS: 36,
} as const

export const MUSCLE_GROUPS = [
  'CHEST', 'BACK', 'SHOULDERS', 'BICEPS', 'TRICEPS', 'FOREARMS',
  'CORE', 'QUADS', 'HAMSTRINGS', 'GLUTES', 'CALVES', 'FULL_BODY', 'CARDIO',
] as const

export const MEAL_TYPES = ['BREAKFAST', 'LUNCH', 'DINNER', 'SNACK'] as const
